import streamlit as st
import streamlit.components.v1 as components

# Streamlit settings
st.set_page_config(layout="wide",page_title="drag")

# Python function to generate content for the left panel


# HTML and CSS for the resizable divider
html_code = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body, html {{
            height: 100%;
            width: 100%;
            overflow: hidden;
        }}
        .container {{
            height: 100%;
            display: flex;
        }}
        .left-panel, .right-panel {{
            flex-grow: 1;
            background-color: lightblue;
            padding: 10px;
        }}
        .resizer {{
            width: 10px;
            background-color: darkgray;
            cursor: col-resize;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="left-panel" id="left-panel">
           <p>This is the left panel.</p>
        </div>
        <div class="resizer"></div>
        <div class="right-panel">
            <p>This is the right panel.</p>
        </div>
    </div>
    <script>
        const resizer = document.querySelector('.resizer');
        const leftPanel = document.querySelector('.left-panel');
        const rightPanel = document.querySelector('.right-panel');
        let isResizing = false;
        resizer.addEventListener('mousedown', (e) => {{
            isResizing = true;
            document.addEventListener('mousemove', onMouseMove);
            document.addEventListener('mouseup', onMouseUp);
        }});
        function onMouseMove(e) {{
            if (!isResizing) return;
            const containerRect = document.querySelector('.container').getBoundingClientRect();
            const newLeftWidth = e.clientX - containerRect.left;
            leftPanel.style.width = `${{newLeftWidth}}px`;
            rightPanel.style.width = `calc(100% - ${{newLeftWidth}}px - ${{resizer.clientWidth}}px)`;
        }}
        function onMouseUp() {{
            isResizing = false;
            document.removeEventListener('mousemove', onMouseMove);
            document.removeEventListener('mouseup', onMouseUp);
        }}
    </script>
</body>
</html>
"""

# Embed the HTML and JavaScript into the Streamlit app
components.html(html_code, height=500)

# Use Streamlit to update the left panel content dynamically
if st.button('Update Left Panel Content'):
    new_content = "<p>This is updated content generated by a Python function.</p>"
    st.write(f"""
    <script>
    document.getElementById("left-panel").innerHTML = `{new_content}`;
    </script>
    """, unsafe_allow_html=True)
